//! # Forensic Reporting Engine
//! 
//! This module handles the transformation of raw analysis results into 
//! professional, human-readable reports in Markdown and JSON formats.
//! 
//! It allows security analysts to quickly export findings for audit purposes.

use std::fs::File;
use std::io::Write;
use std::path::Path;
use crate::error::AnalyzerError;
use crate::SecurityVerdict;

/// Configuration for the reporting engine.
pub struct ReportConfig {
    pub include_stats: bool,
    pub include_hashes: bool,
    pub verbose: bool,
}

impl Default for ReportConfig {
    fn default() -> Self {
        Self {
            include_stats: true,
            include_hashes: true,
            verbose: false,
        }
    }
}

/// The Markdown reporter structure.
pub struct MarkdownReporter {
    config: ReportConfig,
}

impl MarkdownReporter {
    pub fn new(config: ReportConfig) -> Self {
        Self { config }
    }

    /// Generates a full markdown report from multiple analysis results.
    /// 
    /// The report includes:
    /// - Professional Header with versioning
    /// - Executive Summary with object counts
    /// - Risk distribution and detailed forensic findings
    /// - Actionable response recommendations based on findings
    pub fn generate_report(&self, results: &[SecurityVerdict]) -> String {
        let mut md = String::new();

        // Standard Report Header with Branding and Versioning information.
        md.push_str("# UEFI Forensics: Security Analysis Report\n\n");
        md.push_str("> Generated by Rust Analyzer v3.0 (Forensic Edition - Pro)\n\n");

        md.push_str("## Executive Summary\n");
        md.push_str(&format!("Total Objects Analyzed: {}\n", results.len()));
        
        let mut critical_count = 0;
        let mut total_hits = 0;
        // Iterate through all analyzed objects to identify high-risk anomalies.
        for res in results {
            match res {
                SecurityVerdict::PE(pe) => {
                    if pe.is_suspicious || pe.ep_is_suspicious { critical_count += 1; }
                }
                SecurityVerdict::SIGNATURES { hits, .. } => {
                    total_hits += hits.len();
                    if hits.iter().any(|h| h.severity == crate::signatures::Severity::Critical || h.severity == crate::signatures::Severity::High) {
                        critical_count += 1;
                    }
                }
                SecurityVerdict::NVRAM { hits, .. } => {
                    total_hits += hits.len();
                    if hits.iter().any(|h| h.severity == crate::nvram::NvramSeverity::Critical || h.severity == crate::nvram::NvramSeverity::High) {
                        critical_count += 1;
                    }
                }
                _ => {}
            }
        }
        
        md.push_str(&format!("- **Critical/High Risk Markers Found:** {}\n", critical_count));
        md.push_str(&format!("- **Total Forensic Hits:** {}\n\n", total_hits));
        
        md.push_str("## Detailed Findings\n\n");

        for (i, res) in results.iter().enumerate() {
            md.push_str(&format!("### Finding #{}: ", i + 1));
            match res {
                SecurityVerdict::PE(pe) => {
                    md.push_str(&format!("PE Module ({})\n", pe.file_path));
                    md.push_str(&format!("- **Entropy Information:** {}\n", pe.entropy_explanation));
                    md.push_str(&format!("- **Entry Point Suspicion:** {}\n", 
                        if pe.ep_is_suspicious { "⚠️ SUSPICIOUS - EP outside standard sections" } else { "✅ Standard" }));
                    md.push_str(&format!("- **IAT Integrity:** {}\n", 
                        if pe.is_suspicious { "⚠️ UNUSUAL (Possible Malware Loader)" } else { "✅ PASS" }));
                }
                SecurityVerdict::NVRAM { variables, hits } => {
                    md.push_str("UEFI NVRAM Variable Store Analysis\n");
                    md.push_str(&format!("- **Variables Scanned:** {}\n", variables.len()));
                    md.push_str(&format!("- **Anomalies Detected:** {}\n", hits.len()));
                    for hit in hits {
                        md.push_str(&format!("  - [{:?}] {}: {}\n", hit.severity, hit.variable_name, hit.description));
                    }
                }
                SecurityVerdict::SIGNATURES { file, hits } => {
                    md.push_str(&format!("Static Signature Scan ({})\n", file));
                    md.push_str(&format!("- **Matches Found:** {}\n", hits.len()));
                    for hit in hits {
                        md.push_str(&format!("  - **{}**: {} (Offset: 0x{:X})\n", hit.signature_name, hit.recommendation, hit.offset));
                    }
                }
                SecurityVerdict::ELF(elf) => {
                    md.push_str("ELF Binary (Linux Loader)\n");
                    md.push_str(&format!("- **Type:** {:?}\n", elf.machine));
                }
                SecurityVerdict::UNKNOWN { file, error } => {
                    md.push_str("Analysis Error\n");
                    md.push_str(&format!("- **Source:** {}\n", file));
                    md.push_str(&format!("- **Error:** {}\n", error));
                }
            }
            md.push_str("\n---\n\n");
        }

        md.push_str("## Forensic Recommendations & Mitigation\n");
        md.push_str("1. **BIOS Integrity:** Critical hits in NVRAM (e.g. MokListTrusted) require a hardware re-flash or factory reset to ensure a clean Secure Boot state.\n");
        md.push_str("2. **Loader Verification:** If a PE module shows suspicious Entry Points, perform dynamic analysis or cross-reference the hash against known firmware databases (e.g., Virustotal firmware).\n");
        md.push_str("3. **SPI Flash Audit:** Consistent Loax/MoonBounce signatures suggest persistent implants on the SPI flash chip; consider chip-level hardware authentication.\n");

        md
    }

    /// Saves the markdown report to a file.
    pub fn save_to_file<P: AsRef<Path>>(&self, path: P, content: &str) -> Result<(), AnalyzerError> {
        let mut file = File::create(path).map_err(|e| AnalyzerError::ParsingError(e.to_string()))?;
        file.write_all(content.as_bytes()).map_err(|e| AnalyzerError::ParsingError(e.to_string()))?;
        Ok(())
    }
}

/// JSON Reporter for programmatic integration.
pub struct JsonReporter;

impl JsonReporter {
    /// Exports the results as a formatted JSON string.
    pub fn export_json(results: &[SecurityVerdict]) -> Result<String, AnalyzerError> {
        serde_json::to_string_pretty(results)
            .map_err(|e| AnalyzerError::ParsingError(format!("JSON Serialization Error: {}", e)))
    }
}
