//! # Forensic Reporting Engine
//! 
//! This module handles the transformation of raw analysis results into 
//! professional, human-readable reports in Markdown and JSON formats.
//! 
//! It allows security analysts to quickly export findings for audit purposes.

use std::fs::File;
use std::io::Write;
use std::path::Path;
use crate::error::AnalyzerError;
use crate::SecurityVerdict;

/// Configuration for the reporting engine.
pub struct ReportConfig {
    pub include_stats: bool,
    pub include_hashes: bool,
    pub verbose: bool,
}

impl Default for ReportConfig {
    fn default() -> Self {
        Self {
            include_stats: true,
            include_hashes: true,
            verbose: false,
        }
    }
}

/// The Markdown reporter structure.
pub struct MarkdownReporter {
    config: ReportConfig,
}

impl MarkdownReporter {
    pub fn new(config: ReportConfig) -> Self {
        Self { config }
    }

    /// Generates a full markdown report from multiple analysis results.
    /// 
    /// The report includes:
    /// - Professional Header with versioning
    /// - Executive Summary with object counts
    /// - Risk distribution and detailed forensic findings
    /// - Actionable response recommendations based on findings
    pub fn generate_report(&self, results: &[SecurityVerdict]) -> String {
        let mut md = String::new();

        // Standard Report Header with Branding and Versioning information.
        md.push_str("# UEFI Forensics: Security Analysis Report\n\n");
        md.push_str("> Generated by Rust Analyzer v2.0 (Forensic Edition)\n\n");

        md.push_str("## Executive Summary\n");
        md.push_str(&format!("Total Objects Analyzed: {}\n", results.len()));
        
        let mut critical_count = 0;
        // Iterate through all analyzed objects to identify high-risk anomalies.
        // We look for specific triggers that indicate malicious behavior.
        for res in results {
             if let SecurityVerdict::PE(pe) = res {
                 // Entropy > 7.5 usually indicates highly packed/encrypted malicious code
                 // sections, which are a hallmark of modern UEFI bootkits.
                 if pe.entropy > 7.5 { critical_count += 1; }
             }
        }
        
        md.push_str(&format!("High-Risk Indicators Found: {}\n\n", critical_count));
        
        md.push_str("## Detailed Findings\n\n");

        for (i, res) in results.iter().enumerate() {
            md.push_str(&format!("### Finding #{}: ", i + 1));
            match res {
                SecurityVerdict::PE(pe) => {
                    md.push_str("PE Binary (UEFI Payload)\n");
                    md.push_str(&format!("- **Entropy:** {:.4}\n", pe.entropy));
                    md.push_str(&format!("- **Sections:** {}\n", pe.section_count));
                    md.push_str(&format!("- **Verdict:** {}\n", if pe.entropy > 7.2 { "⚠️ SUSPICIOUS (Possible Packing)" } else { "✅ PASS" }));
                }
                SecurityVerdict::ELF(elf) => {
                    md.push_str("ELF Binary (Linux Loader)\n");
                    md.push_str(&format!("- **Type:** {:?}\n", elf.machine));
                }
                SecurityVerdict::UNKNOWN { file, error } => {
                    md.push_str("Analysis Error\n");
                    md.push_str(&format!("- **Source:** {}\n", file));
                    md.push_str(&format!("- **Error:** {}\n", error));
                }
            }
            md.push_str("\n---\n\n");
        }

        md.push_str("## Forensic Recommendations\n");
        md.push_str("1. If high entropy sections are detected without symbols, investigate for custom obfuscation.\n");
        md.push_str("2. Cross-reference IAT import counts with known legitimate firmware baseline.\n");

        md
    }

    /// Saves the markdown report to a file.
    pub fn save_to_file<P: AsRef<Path>>(&self, path: P, content: &str) -> Result<(), AnalyzerError> {
        let mut file = File::create(path).map_err(|e| AnalyzerError::ParsingError(e.to_string()))?;
        file.write_all(content.as_bytes()).map_err(|e| AnalyzerError::ParsingError(e.to_string()))?;
        Ok(())
    }
}

/// JSON Reporter for programmatic integration.
pub struct JsonReporter;

impl JsonReporter {
    /// Exports the results as a formatted JSON string.
    pub fn export_json(results: &[SecurityVerdict]) -> Result<String, AnalyzerError> {
        serde_json::to_string_pretty(results)
            .map_err(|e| AnalyzerError::ParsingError(format!("JSON Serialization Error: {}", e)))
    }
}
